'use strict';

/**
 * @ngdoc function
 * @name admissionSystemApp.controller:MainCtrl
 * @description
 * # MainCtrl
 * Controller of the admissionSystemApp
 */
angular.module('admissionSystemApp')
  .controller('ListProposalCtrl', function ($scope) {
    $scope.awesomeThings = [
      'HTML5 Boilerplate',
      'AngularJS',
      'Karma'
    ];
  });

angular.module('admissionSystemApp')
  .controller('PaginationCtrl', ['$scope', 'ngTableParams', function($scope, ngTableParams) {
    var data = [
      {
        "specialityID": "6.01.0",
        "departmentID": "Math",
        "timePeriodId": 5,
        "specofferTypeId": 2349.66,
        "docSeries": 3534.49,
        "docNum": 21,
        "eduFormTypeId": "vechirna",
        "licCount": 121,
        "stateCount": 77,
        "begDate": "5/05/2022",
        "endDate": "3/03/2014",
        "parentId": "ZIDOX"
      },
      {
        "specialityID": "6.01.1",
        "departmentID": "Legal",
        "timePeriodId": 1,
        "specofferTypeId": 2827.77,
        "docSeries": 2402.15,
        "docNum": 23,
        "eduFormTypeId": "vechirna",
        "licCount": 140,
        "stateCount": 81,
        "begDate": "5/05/2022",
        "endDate": "4/04/2014",
        "parentId": "EPLOSION"
      },
      {
        "specialityID": "6.01.2",
        "departmentID": "Finance",
        "timePeriodId": 3,
        "specofferTypeId": 3219.81,
        "docSeries": 1016.75,
        "docNum": 30,
        "eduFormTypeId": "vechirna",
        "licCount": 68,
        "stateCount": 70,
        "begDate": "2/02/2019",
        "endDate": "1/01/2014",
        "parentId": "INTERODEO"
      },
      {
        "specialityID": "6.01.3",
        "departmentID": "Math",
        "timePeriodId": 2,
        "specofferTypeId": 3627.38,
        "docSeries": 2527.74,
        "docNum": 20,
        "eduFormTypeId": "denna",
        "licCount": 156,
        "stateCount": 58,
        "begDate": "2/02/2019",
        "endDate": "1/01/2014",
        "parentId": "PAPRIKUT"
      },
      {
        "specialityID": "6.01.4",
        "departmentID": "Legal",
        "timePeriodId": 1,
        "specofferTypeId": 3336.56,
        "docSeries": 3658.96,
        "docNum": 28,
        "eduFormTypeId": "zaochna",
        "licCount": 146,
        "stateCount": 61,
        "begDate": "3/03/2020",
        "endDate": "5/05/2014",
        "parentId": "TUBALUM"
      },
      {
        "specialityID": "6.01.5",
        "departmentID": "Math",
        "timePeriodId": 2,
        "specofferTypeId": 2346.02,
        "docSeries": 3705.58,
        "docNum": 33,
        "eduFormTypeId": "zaochna",
        "licCount": 160,
        "stateCount": 97,
        "begDate": "3/03/2020",
        "endDate": "3/03/2014",
        "parentId": "CALCULA"
      },
      {
        "specialityID": "6.01.6",
        "departmentID": "Finance",
        "timePeriodId": 1,
        "specofferTypeId": 2761.4,
        "docSeries": 1255.62,
        "docNum": 36,
        "eduFormTypeId": "zaochna",
        "licCount": 134,
        "stateCount": 57,
        "begDate": "3/03/2020",
        "endDate": "5/05/2014",
        "parentId": "COSMETEX"
      },
      {
        "specialityID": "6.01.7",
        "departmentID": "Math",
        "timePeriodId": 4,
        "specofferTypeId": 3626,
        "docSeries": 3646,
        "docNum": 29,
        "eduFormTypeId": "zaochna",
        "licCount": 143,
        "stateCount": 54,
        "begDate": "4/04/2021",
        "endDate": "5/05/2014",
        "parentId": "VERTIDE"
      },
      {
        "specialityID": "6.01.8",
        "departmentID": "Math",
        "timePeriodId": 4,
        "specofferTypeId": 2896.52,
        "docSeries": 2973.54,
        "docNum": 38,
        "eduFormTypeId": "zaochna",
        "licCount": 153,
        "stateCount": 96,
        "begDate": "5/05/2022",
        "endDate": "1/01/2014",
        "parentId": "QUONATA"
      },
      {
        "specialityID": "6.01.9",
        "departmentID": "Finance",
        "timePeriodId": 4,
        "specofferTypeId": 3831.47,
        "docSeries": 2920.91,
        "docNum": 21,
        "eduFormTypeId": "zaochna",
        "licCount": 107,
        "stateCount": 60,
        "begDate": "2/02/2019",
        "endDate": "4/04/2014",
        "parentId": "BLUPLANET"
      },
      {
        "specialityID": "6.01.10",
        "departmentID": "Finance",
        "timePeriodId": 2,
        "specofferTypeId": 2384.06,
        "docSeries": 1624.84,
        "docNum": 24,
        "eduFormTypeId": "denna",
        "licCount": 70,
        "stateCount": 91,
        "begDate": "5/05/2022",
        "endDate": "2/02/2014",
        "parentId": "KOOGLE"
      },
      {
        "specialityID": "6.01.11",
        "departmentID": "Finance",
        "timePeriodId": 3,
        "specofferTypeId": 2113.51,
        "docSeries": 3072.51,
        "docNum": 33,
        "eduFormTypeId": "vechirna",
        "licCount": 156,
        "stateCount": 91,
        "begDate": "1/01/2018",
        "endDate": "4/04/2014",
        "parentId": "EXERTA"
      },
      {
        "specialityID": "6.01.12",
        "departmentID": "Math",
        "timePeriodId": 2,
        "specofferTypeId": 1712.47,
        "docSeries": 3430.01,
        "docNum": 27,
        "eduFormTypeId": "vechirna",
        "licCount": 157,
        "stateCount": 90,
        "begDate": "2/02/2019",
        "endDate": "2/02/2014",
        "parentId": "PROSELY"
      },
      {
        "specialityID": "6.01.13",
        "departmentID": "Finance",
        "timePeriodId": 2,
        "specofferTypeId": 2545.07,
        "docSeries": 2014.49,
        "docNum": 22,
        "eduFormTypeId": "denna",
        "licCount": 83,
        "stateCount": 59,
        "begDate": "4/04/2021",
        "endDate": "1/01/2014",
        "parentId": "QUONK"
      },
      {
        "specialityID": "6.01.14",
        "departmentID": "Math",
        "timePeriodId": 4,
        "specofferTypeId": 1383.23,
        "docSeries": 2157.9,
        "docNum": 27,
        "eduFormTypeId": "denna",
        "licCount": 148,
        "stateCount": 74,
        "begDate": "5/05/2022",
        "endDate": "5/05/2014",
        "parentId": "EARTHPURE"
      },
      {
        "specialityID": "6.01.15",
        "departmentID": "Legal",
        "timePeriodId": 3,
        "specofferTypeId": 1086.7,
        "docSeries": 3673.03,
        "docNum": 39,
        "eduFormTypeId": "zaochna",
        "licCount": 140,
        "stateCount": 73,
        "begDate": "5/05/2022",
        "endDate": "5/05/2014",
        "parentId": "PHUEL"
      },
      {
        "specialityID": "6.01.16",
        "departmentID": "Legal",
        "timePeriodId": 5,
        "specofferTypeId": 2798.82,
        "docSeries": 2329.86,
        "docNum": 36,
        "eduFormTypeId": "vechirna",
        "licCount": 56,
        "stateCount": 98,
        "begDate": "3/03/2020",
        "endDate": "2/02/2014",
        "parentId": "ULTRIMAX"
      },
      {
        "specialityID": "6.01.17",
        "departmentID": "Legal",
        "timePeriodId": 3,
        "specofferTypeId": 3811.2,
        "docSeries": 1348.83,
        "docNum": 29,
        "eduFormTypeId": "denna",
        "licCount": 93,
        "stateCount": 88,
        "begDate": "5/05/2022",
        "endDate": "1/01/2014",
        "parentId": "TECHTRIX"
      },
      {
        "specialityID": "6.01.18",
        "departmentID": "Finance",
        "timePeriodId": 1,
        "specofferTypeId": 3809.09,
        "docSeries": 3193.43,
        "docNum": 38,
        "eduFormTypeId": "denna",
        "licCount": 142,
        "stateCount": 67,
        "begDate": "1/01/2018",
        "endDate": "4/04/2014",
        "parentId": "GOGOL"
      },
      {
        "specialityID": "6.01.19",
        "departmentID": "Finance",
        "timePeriodId": 4,
        "specofferTypeId": 3450.67,
        "docSeries": 1534.78,
        "docNum": 30,
        "eduFormTypeId": "zaochna",
        "licCount": 116,
        "stateCount": 63,
        "begDate": "2/02/2019",
        "endDate": "5/05/2014",
        "parentId": "KRAGGLE"
      },
      {
        "specialityID": "6.01.20",
        "departmentID": "Legal",
        "timePeriodId": 4,
        "specofferTypeId": 3098.46,
        "docSeries": 2408.43,
        "docNum": 24,
        "eduFormTypeId": "zaochna",
        "licCount": 155,
        "stateCount": 78,
        "begDate": "1/01/2018",
        "endDate": "5/05/2014",
        "parentId": "SHEPARD"
      },
      {
        "specialityID": "6.01.21",
        "departmentID": "Legal",
        "timePeriodId": 5,
        "specofferTypeId": 2934.32,
        "docSeries": 3894.99,
        "docNum": 28,
        "eduFormTypeId": "zaochna",
        "licCount": 102,
        "stateCount": 63,
        "begDate": "2/02/2019",
        "endDate": "2/02/2014",
        "parentId": "ZOXY"
      },
      {
        "specialityID": "6.01.22",
        "departmentID": "Math",
        "timePeriodId": 5,
        "specofferTypeId": 2310.16,
        "docSeries": 1844.42,
        "docNum": 24,
        "eduFormTypeId": "denna",
        "licCount": 137,
        "stateCount": 61,
        "begDate": "2/02/2019",
        "endDate": "1/01/2014",
        "parentId": "BALUBA"
      },
      {
        "specialityID": "6.01.23",
        "departmentID": "Math",
        "timePeriodId": 5,
        "specofferTypeId": 2158.33,
        "docSeries": 1801.79,
        "docNum": 34,
        "eduFormTypeId": "vechirna",
        "licCount": 88,
        "stateCount": 69,
        "begDate": "3/03/2020",
        "endDate": "4/04/2014",
        "parentId": "EMERGENT"
      },
      {
        "specialityID": "6.01.24",
        "departmentID": "Legal",
        "timePeriodId": 4,
        "specofferTypeId": 2986.2,
        "docSeries": 3563.19,
        "docNum": 37,
        "eduFormTypeId": "vechirna",
        "licCount": 58,
        "stateCount": 55,
        "begDate": "2/02/2019",
        "endDate": "4/04/2014",
        "parentId": "NORSUL"
      },
      {
        "specialityID": "6.01.25",
        "departmentID": "Legal",
        "timePeriodId": 2,
        "specofferTypeId": 2771.29,
        "docSeries": 3236.53,
        "docNum": 39,
        "eduFormTypeId": "denna",
        "licCount": 138,
        "stateCount": 60,
        "begDate": "3/03/2020",
        "endDate": "3/03/2014",
        "parentId": "AQUOAVO"
      },
      {
        "specialityID": "6.01.26",
        "departmentID": "Math",
        "timePeriodId": 2,
        "specofferTypeId": 1053.46,
        "docSeries": 2953.44,
        "docNum": 24,
        "eduFormTypeId": "zaochna",
        "licCount": 85,
        "stateCount": 95,
        "begDate": "4/04/2021",
        "endDate": "1/01/2014",
        "parentId": "GALLAXIA"
      },
      {
        "specialityID": "6.01.27",
        "departmentID": "Finance",
        "timePeriodId": 3,
        "specofferTypeId": 1269.17,
        "docSeries": 3987.23,
        "docNum": 26,
        "eduFormTypeId": "zaochna",
        "licCount": 160,
        "stateCount": 83,
        "begDate": "2/02/2019",
        "endDate": "1/01/2014",
        "parentId": "MULTRON"
      },
      {
        "specialityID": "6.01.28",
        "departmentID": "Finance",
        "timePeriodId": 4,
        "specofferTypeId": 2706.06,
        "docSeries": 3097.44,
        "docNum": 30,
        "eduFormTypeId": "vechirna",
        "licCount": 98,
        "stateCount": 55,
        "begDate": "3/03/2020",
        "endDate": "1/01/2014",
        "parentId": "ISBOL"
      },
      {
        "specialityID": "6.01.29",
        "departmentID": "Math",
        "timePeriodId": 3,
        "specofferTypeId": 2173.87,
        "docSeries": 1923.89,
        "docNum": 39,
        "eduFormTypeId": "zaochna",
        "licCount": 154,
        "stateCount": 65,
        "begDate": "5/05/2022",
        "endDate": "1/01/2014",
        "parentId": "EXOSTREAM"
      },
      {
        "specialityID": "6.01.30",
        "departmentID": "Finance",
        "timePeriodId": 1,
        "specofferTypeId": 2123.24,
        "docSeries": 2780,
        "docNum": 26,
        "eduFormTypeId": "denna",
        "licCount": 58,
        "stateCount": 79,
        "begDate": "1/01/2018",
        "endDate": "3/03/2014",
        "parentId": "IMMUNICS"
      },
      {
        "specialityID": "6.01.31",
        "departmentID": "Legal",
        "timePeriodId": 5,
        "specofferTypeId": 2516.76,
        "docSeries": 3696.76,
        "docNum": 33,
        "eduFormTypeId": "zaochna",
        "licCount": 126,
        "stateCount": 69,
        "begDate": "2/02/2019",
        "endDate": "4/04/2014",
        "parentId": "CAXT"
      },
      {
        "specialityID": "6.01.32",
        "departmentID": "Finance",
        "timePeriodId": 4,
        "specofferTypeId": 3519.59,
        "docSeries": 2100.39,
        "docNum": 25,
        "eduFormTypeId": "denna",
        "licCount": 128,
        "stateCount": 55,
        "begDate": "4/04/2021",
        "endDate": "5/05/2014",
        "parentId": "ASSURITY"
      },
      {
        "specialityID": "6.01.33",
        "departmentID": "Math",
        "timePeriodId": 4,
        "specofferTypeId": 3266.44,
        "docSeries": 2487.51,
        "docNum": 24,
        "eduFormTypeId": "denna",
        "licCount": 150,
        "stateCount": 73,
        "begDate": "3/03/2020",
        "endDate": "4/04/2014",
        "parentId": "CEPRENE"
      },
      {
        "specialityID": "6.01.34",
        "departmentID": "Finance",
        "timePeriodId": 4,
        "specofferTypeId": 3550.73,
        "docSeries": 3416.11,
        "docNum": 22,
        "eduFormTypeId": "zaochna",
        "licCount": 159,
        "stateCount": 53,
        "begDate": "4/04/2021",
        "endDate": "5/05/2014",
        "parentId": "NETBOOK"
      },
      {
        "specialityID": "6.01.35",
        "departmentID": "Legal",
        "timePeriodId": 5,
        "specofferTypeId": 2725.25,
        "docSeries": 1446.24,
        "docNum": 29,
        "eduFormTypeId": "denna",
        "licCount": 77,
        "stateCount": 98,
        "begDate": "4/04/2021",
        "endDate": "4/04/2014",
        "parentId": "SULFAX"
      },
      {
        "specialityID": "6.01.36",
        "departmentID": "Math",
        "timePeriodId": 5,
        "specofferTypeId": 2092.71,
        "docSeries": 1334.71,
        "docNum": 24,
        "eduFormTypeId": "denna",
        "licCount": 108,
        "stateCount": 62,
        "begDate": "3/03/2020",
        "endDate": "4/04/2014",
        "parentId": "INRT"
      },
      {
        "specialityID": "6.01.37",
        "departmentID": "Legal",
        "timePeriodId": 1,
        "specofferTypeId": 2273.59,
        "docSeries": 1168.49,
        "docNum": 23,
        "eduFormTypeId": "vechirna",
        "licCount": 119,
        "stateCount": 62,
        "begDate": "4/04/2021",
        "endDate": "4/04/2014",
        "parentId": "DAISU"
      },
      {
        "specialityID": "6.01.38",
        "departmentID": "Math",
        "timePeriodId": 5,
        "specofferTypeId": 3877.39,
        "docSeries": 2676.16,
        "docNum": 29,
        "eduFormTypeId": "vechirna",
        "licCount": 89,
        "stateCount": 64,
        "begDate": "1/01/2018",
        "endDate": "5/05/2014",
        "parentId": "ZENSOR"
      },
      {
        "specialityID": "6.01.39",
        "departmentID": "Finance",
        "timePeriodId": 3,
        "specofferTypeId": 3164.48,
        "docSeries": 1007.47,
        "docNum": 27,
        "eduFormTypeId": "zaochna",
        "licCount": 123,
        "stateCount": 79,
        "begDate": "4/04/2021",
        "endDate": "3/03/2014",
        "parentId": "BUZZNESS"
      },
      {
        "specialityID": "6.01.40",
        "departmentID": "Finance",
        "timePeriodId": 5,
        "specofferTypeId": 3398.35,
        "docSeries": 3752.73,
        "docNum": 32,
        "eduFormTypeId": "vechirna",
        "licCount": 149,
        "stateCount": 76,
        "begDate": "5/05/2022",
        "endDate": "2/02/2014",
        "parentId": "ISOTRACK"
      },
      {
        "specialityID": "6.01.41",
        "departmentID": "Finance",
        "timePeriodId": 2,
        "specofferTypeId": 1362.69,
        "docSeries": 3175.32,
        "docNum": 36,
        "eduFormTypeId": "vechirna",
        "licCount": 136,
        "stateCount": 88,
        "begDate": "4/04/2021",
        "endDate": "3/03/2014",
        "parentId": "JIMBIES"
      },
      {
        "specialityID": "6.01.42",
        "departmentID": "Math",
        "timePeriodId": 3,
        "specofferTypeId": 2903.77,
        "docSeries": 3957.19,
        "docNum": 31,
        "eduFormTypeId": "vechirna",
        "licCount": 154,
        "stateCount": 95,
        "begDate": "1/01/2018",
        "endDate": "3/03/2014",
        "parentId": "FRENEX"
      },
      {
        "specialityID": "6.01.43",
        "departmentID": "Finance",
        "timePeriodId": 3,
        "specofferTypeId": 2683.57,
        "docSeries": 1465.5,
        "docNum": 26,
        "eduFormTypeId": "vechirna",
        "licCount": 140,
        "stateCount": 91,
        "begDate": "1/01/2018",
        "endDate": "5/05/2014",
        "parentId": "IMKAN"
      },
      {
        "specialityID": "6.01.44",
        "departmentID": "Finance",
        "timePeriodId": 4,
        "specofferTypeId": 3162.21,
        "docSeries": 2512.3,
        "docNum": 23,
        "eduFormTypeId": "denna",
        "licCount": 54,
        "stateCount": 74,
        "begDate": "1/01/2018",
        "endDate": "5/05/2014",
        "parentId": "SPACEWAX"
      },
      {
        "specialityID": "6.01.45",
        "departmentID": "Legal",
        "timePeriodId": 3,
        "specofferTypeId": 1716.04,
        "docSeries": 1025.15,
        "docNum": 31,
        "eduFormTypeId": "vechirna",
        "licCount": 92,
        "stateCount": 52,
        "begDate": "5/05/2022",
        "endDate": "5/05/2014",
        "parentId": "ISOPOP"
      },
      {
        "specialityID": "6.01.46",
        "departmentID": "Math",
        "timePeriodId": 1,
        "specofferTypeId": 1026.57,
        "docSeries": 1315.62,
        "docNum": 20,
        "eduFormTypeId": "denna",
        "licCount": 100,
        "stateCount": 84,
        "begDate": "3/03/2020",
        "endDate": "1/01/2014",
        "parentId": "MEMORA"
      },
      {
        "specialityID": "6.01.47",
        "departmentID": "Finance",
        "timePeriodId": 2,
        "specofferTypeId": 1212.85,
        "docSeries": 2921.16,
        "docNum": 22,
        "eduFormTypeId": "zaochna",
        "licCount": 65,
        "stateCount": 74,
        "begDate": "4/04/2021",
        "endDate": "2/02/2014",
        "parentId": "AUSTEX"
      },
      {
        "specialityID": "6.01.48",
        "departmentID": "Finance",
        "timePeriodId": 4,
        "specofferTypeId": 2629.07,
        "docSeries": 3113.49,
        "docNum": 32,
        "eduFormTypeId": "vechirna",
        "licCount": 82,
        "stateCount": 99,
        "begDate": "3/03/2020",
        "endDate": "5/05/2014",
        "parentId": "MUSIX"
      },
      {
        "specialityID": "6.01.49",
        "departmentID": "Legal",
        "timePeriodId": 2,
        "specofferTypeId": 1797.54,
        "docSeries": 2278.55,
        "docNum": 21,
        "eduFormTypeId": "denna",
        "licCount": 136,
        "stateCount": 70,
        "begDate": "2/02/2019",
        "endDate": "2/02/2014",
        "parentId": "SUPREMIA"
      },
      {
        "specialityID": "6.01.50",
        "departmentID": "Legal",
        "timePeriodId": 2,
        "specofferTypeId": 3316,
        "docSeries": 3756.64,
        "docNum": 22,
        "eduFormTypeId": "denna",
        "licCount": 83,
        "stateCount": 82,
        "begDate": "3/03/2020",
        "endDate": "5/05/2014",
        "parentId": "NSPIRE"
      },
      {
        "specialityID": "6.01.51",
        "departmentID": "Legal",
        "timePeriodId": 2,
        "specofferTypeId": 1974.06,
        "docSeries": 1522.38,
        "docNum": 35,
        "eduFormTypeId": "denna",
        "licCount": 121,
        "stateCount": 54,
        "begDate": "4/04/2021",
        "endDate": "1/01/2014",
        "parentId": "HANDSHAKE"
      },
      {
        "specialityID": "6.01.52",
        "departmentID": "Legal",
        "timePeriodId": 5,
        "specofferTypeId": 2176.89,
        "docSeries": 3027.1,
        "docNum": 20,
        "eduFormTypeId": "zaochna",
        "licCount": 139,
        "stateCount": 62,
        "begDate": "1/01/2018",
        "endDate": "3/03/2014",
        "parentId": "SYNKGEN"
      },
      {
        "specialityID": "6.01.53",
        "departmentID": "Math",
        "timePeriodId": 4,
        "specofferTypeId": 1528.77,
        "docSeries": 1725.82,
        "docNum": 25,
        "eduFormTypeId": "denna",
        "licCount": 145,
        "stateCount": 66,
        "begDate": "1/01/2018",
        "endDate": "5/05/2014",
        "parentId": "ZYTREX"
      },
      {
        "specialityID": "6.01.54",
        "departmentID": "Legal",
        "timePeriodId": 4,
        "specofferTypeId": 2235.89,
        "docSeries": 1482.18,
        "docNum": 34,
        "eduFormTypeId": "vechirna",
        "licCount": 76,
        "stateCount": 92,
        "begDate": "4/04/2021",
        "endDate": "4/04/2014",
        "parentId": "ROCKYARD"
      },
      {
        "specialityID": "6.01.55",
        "departmentID": "Finance",
        "timePeriodId": 1,
        "specofferTypeId": 1488.46,
        "docSeries": 1258,
        "docNum": 20,
        "eduFormTypeId": "denna",
        "licCount": 110,
        "stateCount": 95,
        "begDate": "1/01/2018",
        "endDate": "4/04/2014",
        "parentId": "QIAO"
      },
      {
        "specialityID": "6.01.56",
        "departmentID": "Legal",
        "timePeriodId": 4,
        "specofferTypeId": 2056.12,
        "docSeries": 2936.17,
        "docNum": 27,
        "eduFormTypeId": "zaochna",
        "licCount": 59,
        "stateCount": 87,
        "begDate": "1/01/2018",
        "endDate": "4/04/2014",
        "parentId": "UNEEQ"
      },
      {
        "specialityID": "6.01.57",
        "departmentID": "Finance",
        "timePeriodId": 5,
        "specofferTypeId": 1839.26,
        "docSeries": 3833.98,
        "docNum": 38,
        "eduFormTypeId": "denna",
        "licCount": 114,
        "stateCount": 94,
        "begDate": "2/02/2019",
        "endDate": "4/04/2014",
        "parentId": "HAIRPORT"
      },
      {
        "specialityID": "6.01.58",
        "departmentID": "Math",
        "timePeriodId": 4,
        "specofferTypeId": 3659.12,
        "docSeries": 2593.75,
        "docNum": 27,
        "eduFormTypeId": "denna",
        "licCount": 93,
        "stateCount": 95,
        "begDate": "5/05/2022",
        "endDate": "5/05/2014",
        "parentId": "HARMONEY"
      },
      {
        "specialityID": "6.01.59",
        "departmentID": "Finance",
        "timePeriodId": 1,
        "specofferTypeId": 2222.94,
        "docSeries": 1697.36,
        "docNum": 29,
        "eduFormTypeId": "vechirna",
        "licCount": 120,
        "stateCount": 75,
        "begDate": "2/02/2019",
        "endDate": "5/05/2014",
        "parentId": "SUREPLEX"
      },
      {
        "specialityID": "6.01.60",
        "departmentID": "Math",
        "timePeriodId": 4,
        "specofferTypeId": 3281.53,
        "docSeries": 1461.64,
        "docNum": 32,
        "eduFormTypeId": "vechirna",
        "licCount": 127,
        "stateCount": 95,
        "begDate": "3/03/2020",
        "endDate": "1/01/2014",
        "parentId": "BICOL"
      },
      {
        "specialityID": "6.01.61",
        "departmentID": "Math",
        "timePeriodId": 4,
        "specofferTypeId": 1805.75,
        "docSeries": 1012.6,
        "docNum": 23,
        "eduFormTypeId": "denna",
        "licCount": 85,
        "stateCount": 87,
        "begDate": "2/02/2019",
        "endDate": "2/02/2014",
        "parentId": "VIXO"
      },
      {
        "specialityID": "6.01.62",
        "departmentID": "Finance",
        "timePeriodId": 5,
        "specofferTypeId": 2580.16,
        "docSeries": 2496.07,
        "docNum": 39,
        "eduFormTypeId": "vechirna",
        "licCount": 139,
        "stateCount": 62,
        "begDate": "4/04/2021",
        "endDate": "2/02/2014",
        "parentId": "LIQUICOM"
      },
      {
        "specialityID": "6.01.63",
        "departmentID": "Math",
        "timePeriodId": 5,
        "specofferTypeId": 2463.77,
        "docSeries": 2609.65,
        "docNum": 33,
        "eduFormTypeId": "zaochna",
        "licCount": 147,
        "stateCount": 56,
        "begDate": "2/02/2019",
        "endDate": "1/01/2014",
        "parentId": "EURON"
      },
      {
        "specialityID": "6.01.64",
        "departmentID": "Math",
        "timePeriodId": 1,
        "specofferTypeId": 2453.9,
        "docSeries": 3993.06,
        "docNum": 34,
        "eduFormTypeId": "vechirna",
        "licCount": 132,
        "stateCount": 52,
        "begDate": "5/05/2022",
        "endDate": "2/02/2014",
        "parentId": "ISOPLEX"
      },
      {
        "specialityID": "6.01.65",
        "departmentID": "Math",
        "timePeriodId": 1,
        "specofferTypeId": 2345.47,
        "docSeries": 3007.48,
        "docNum": 26,
        "eduFormTypeId": "denna",
        "licCount": 93,
        "stateCount": 59,
        "begDate": "4/04/2021",
        "endDate": "3/03/2014",
        "parentId": "ELECTONIC"
      },
      {
        "specialityID": "6.01.66",
        "departmentID": "Finance",
        "timePeriodId": 4,
        "specofferTypeId": 1677.73,
        "docSeries": 3997.73,
        "docNum": 27,
        "eduFormTypeId": "zaochna",
        "licCount": 100,
        "stateCount": 84,
        "begDate": "2/02/2019",
        "endDate": "4/04/2014",
        "parentId": "GEEKNET"
      },
      {
        "specialityID": "6.01.67",
        "departmentID": "Legal",
        "timePeriodId": 5,
        "specofferTypeId": 2757.96,
        "docSeries": 1146.38,
        "docNum": 28,
        "eduFormTypeId": "vechirna",
        "licCount": 159,
        "stateCount": 63,
        "begDate": "1/01/2018",
        "endDate": "4/04/2014",
        "parentId": "HATOLOGY"
      },
      {
        "specialityID": "6.01.68",
        "departmentID": "Legal",
        "timePeriodId": 5,
        "specofferTypeId": 2038.94,
        "docSeries": 1995.55,
        "docNum": 23,
        "eduFormTypeId": "zaochna",
        "licCount": 130,
        "stateCount": 75,
        "begDate": "2/02/2019",
        "endDate": "2/02/2014",
        "parentId": "ACCIDENCY"
      }];
    $scope.tableParams = new ngTableParams({
      page: 1,            // show first page
      count: 10           // count per page
    }, {
      total: data.length, // length of data
      getData: function($defer, params) {
        $defer.resolve(data.slice((params.page() - 1) * params.count(), params.page() * params.count()));
      }
    });
  }]);

